language: node_js # 设置语言
node_js: stable # 设置相应版本

cache:
    directories:
        - node_modules # 缓存不经常更改的内容
    
# env:
#     global:
        # - GITHUB_URL: github.com/wjsaya/wjsaya.github.io.git #设置GITHUB_URL
        # - CODING_URL: git.coding.net/wjsaya/wjsaya.git

branches:
    only:
        - hexo # 只监测hexo分支

install:
    - npm install # 安装hexo及插件

before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm cache verify
    - npm install npm -g
    - npm install hexo-cli -g  # 安装hexo环境

script:
    - hexo clean # 清除
    - hexo generate # 生成

after_script:
  - sed -i "s/AUTO_GH_TOKEN/${hexo_token}/g" ./_config.yml
  - hexo deploy
  # 不手动执行，直接通过hexo deploy来调用_config.yml发布
  
    # - git clone https://${GITHUB_URL} .deploy_git
    # - # add commit timestamp
    # - git add .
    # - git commit -m "Travis CI Auto Build at `date +"%Y-%m-%d %H:%M"`"
    # - git push --force --quiet "https://${hexo_token}@${GITHUB_URL}" master:master
    # - git push --force --quiet "https://hadronw:${Travis_co_token}@${CODING_URL}" master:master
